import Head from "next/head";
import Image from "next/image";
import Cta from "../components/Cta";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import MoreInfoModal from "../components/Moreinfo";
import MoreInfo from "../components/Moreinfo";
import Navbar from "../components/Navbar";
import Teacher from "../components/Member";
import Values from "../components/Values";
import About from "../components/About";

export default function Home() {
  return (
    <div className='scroll-smooth' >
      <Head>
        <title>Blendtopia</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@200;300;400;500;600;700;800;900&display=swap"
          rel="stylesheet"
        ></link>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    <Hero/>
    <div className="bg-">
    <Values/>
    <About/>
    </div>
    <Teacher/>
   <MoreInfoModal/>
   <Cta/>
   <Footer/>
    </div>
  );
}
